In [1]:
import numpy as np

In [ ]:
l=[1,2,3,4]

In [ ]:
ar=np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
a=[1,2,3]

In [11]:
np.asanyarray(a)

array([1, 2, 3])

In [12]:
c=a

In [13]:
c

[1, 2, 3]

In [14]:
d=np.copy(a)

In [15]:
d

array([1, 2, 3])

In [16]:
a[2]=300

In [18]:
a

[1, 2, 300]

In [7]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [9]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [12]:
iterable=(i*i for i in range(6))

In [13]:
np.fromiter(iterable ,float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [16]:
np.fromstring('123 456' ,sep=' ')

array([123., 456.])

In [17]:
np.fromstring('1 2' ,sep=' ')

array([1., 2.])

In [2]:
np.fromfunction(lambda i,j : i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [3]:
np.fromfunction(lambda i,j : i==j ,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [6]:
iterable1=(i*i for i in range(7))

In [7]:
np.fromiter(iterable1 ,int)

array([ 0,  1,  4,  9, 16, 25, 36])

In [8]:
#numpy-data types

In [2]:
m=[1,2,3,4,5]

In [3]:
ar=np.array(m)

In [4]:
ar

array([1, 2, 3, 4, 5])

In [5]:
ar.ndim

1

In [12]:
ar1=np.array([[9,8,7,6,5] ,[1,2,3,4,5]])

In [13]:
ar1

array([[9, 8, 7, 6, 5],
       [1, 2, 3, 4, 5]])

In [14]:
ar1.ndim

2

In [15]:
ar1.size

10

In [16]:
ar.shape

(5,)

In [17]:
ar1.shape

(2, 5)

In [18]:
ar.dtype

dtype('int64')

In [19]:
ar2=np.array([[1,2,3,4.8] ,[8,7,4,5]])

In [20]:
ar2

array([[1. , 2. , 3. , 4.8],
       [8. , 7. , 4. , 5. ]])

In [21]:
ar2.dtype

dtype('float64')

In [24]:
list(range(0.1 ,0.7))

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.arange(0.1 ,5.7)

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1])

In [1]:
import numpy as np

In [3]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
np.arange(2.1 , 7.1)

array([2.1, 3.1, 4.1, 5.1, 6.1])

In [1]:
import numpy as np

In [2]:
list(np.arange(7.1 ,21.7))

[7.1,
 8.1,
 9.1,
 10.1,
 11.1,
 12.1,
 13.1,
 14.1,
 15.1,
 16.1,
 17.1,
 18.1,
 19.1,
 20.1,
 21.1]

In [1]:
import numpy as np

In [5]:
np.linspace(1,6,12)

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
ar = np.zeros((3,4))

In [11]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ar.ndim

2

In [14]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
ar5=np.ones(5)

In [17]:
ar5

array([1., 1., 1., 1., 1.])

In [18]:
ar5.ndim

1

In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
ar6=np.ones((2,4,5))

In [22]:
ar6

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
ar6+2

array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]])

In [24]:
ar6.ndim

3

In [26]:
ar6*4

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [29]:
np.empty(2)

array([2.00000000e+000, 6.95269913e-310])

In [1]:
import numpy as np

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.empty(5)

array([4.68300338e-310, 0.00000000e+000, 4.68234230e-310, 4.68234230e-310,
       2.37151510e-322])

In [5]:
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr=np.random.randn(3,4)

In [7]:
import pandas as pd 

In [8]:
pd.DataFrame(arr)

0         1         2         3
0 -1.553110 -0.381975  1.569868  0.010397
1  0.051949  2.323944  0.138646  2.398728
2 -0.203509 -1.142780 -1.453209  1.663771

In [9]:
np.random.rand(3,4)

array([[0.08933932, 0.20864737, 0.29057038, 0.84804077],
       [0.29653812, 0.70497784, 0.18441241, 0.9152215 ],
       [0.96952644, 0.68921321, 0.02282121, 0.02894459]])

In [21]:
pd.DataFrame(np.random.randint(1,100 ,(4,5))).to_csv('test.csv')

In [29]:
az

NameError: name 'az' is not defined

In [27]:
ar.reshape(6,2)

ValueError: cannot reshape array of size 20 into shape (6,2)

In [1]:
import numpy as np

In [2]:
at=np.random.rand(4,5)

In [3]:
at

array([[0.05893319, 0.67427846, 0.27949308, 0.66251613, 0.95581569],
       [0.11055876, 0.21024763, 0.11581205, 0.38735176, 0.05665341],
       [0.34792373, 0.55383168, 0.32907187, 0.19416402, 0.08768719],
       [0.36855914, 0.68613846, 0.83751709, 0.85041003, 0.73320818]])

In [5]:
at1=at.reshape(10,2)

In [6]:
at1

array([[0.05893319, 0.67427846],
       [0.27949308, 0.66251613],
       [0.95581569, 0.11055876],
       [0.21024763, 0.11581205],
       [0.38735176, 0.05665341],
       [0.34792373, 0.55383168],
       [0.32907187, 0.19416402],
       [0.08768719, 0.36855914],
       [0.68613846, 0.83751709],
       [0.85041003, 0.73320818]])

In [8]:
at1[2][0]

0.9558156874794925

In [9]:
at1[1][1]

0.6625161267598813

In [13]:
at3=np.random.randint(1,200 ,(4,5))

In [14]:
at3

array([[ 62,  33, 193, 195,  76],
       [156, 150, 178,  63,  55],
       [173, 173,   9,  98, 199],
       [142, 107,  65,  98, 120]])

In [15]:
at3>100

array([[False, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False,  True]])

In [16]:
at3[at3>100]

array([193, 195, 156, 150, 178, 173, 173, 199, 142, 107, 120])

In [19]:
at3[1:4:1]

array([[156, 150, 178,  63,  55],
       [173, 173,   9,  98, 199],
       [142, 107,  65,  98, 120]])

In [20]:
at3[1:3 ,[0,1]]

array([[156, 150],
       [173, 173]])

In [21]:
at4=np.random.randint(1,4 ,(3,3))
at5=np.random.randint(2,6 ,(3,3))

In [22]:
at4

array([[3, 3, 1],
       [1, 3, 3],
       [2, 2, 3]])

In [23]:
at5

array([[4, 5, 4],
       [4, 5, 5],
       [3, 3, 4]])

In [25]:
at6=at4+at5

In [26]:
at6

array([[7, 8, 5],
       [5, 8, 8],
       [5, 5, 7]])

In [28]:
at6[1:2 ,[1,2]]

array([[8, 8]])

In [29]:
at4*at5

array([[12, 15,  4],
       [ 4, 15, 15],
       [ 6,  6, 12]])

In [30]:
at4-at5

array([[-1, -2, -3],
       [-3, -2, -2],
       [-1, -1, -1]])

In [31]:
at4/at5

array([[0.75      , 0.6       , 0.25      ],
       [0.25      , 0.6       , 0.6       ],
       [0.66666667, 0.66666667, 0.75      ]])

In [32]:
at4@at5

array([[27, 33, 31],
       [25, 29, 31],
       [25, 29, 30]])

In [33]:
#numpy-Broadcasting

In [35]:
at7=np.zeros((3,3))

In [36]:
at7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
at8=np.array([7,8,9])

In [38]:
at8

array([7, 8, 9])

In [39]:
at7+at8

array([[7., 8., 9.],
       [7., 8., 9.],
       [7., 8., 9.]])

In [44]:
at9=np.array([[1,2,3]])

In [45]:
at9

array([[1, 2, 3]])

In [47]:
at10=at9.T

In [48]:
at10

array([[1],
       [2],
       [3]])

In [49]:
at7+at10

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [50]:
at11=np.random.randint(1,3 ,(3,3))

In [51]:
at11

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [52]:
np.sqrt(at11)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [53]:
np.exp(at11)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [54]:
np.log2(at11)

array([[0., 1., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])